[project]
name = "alcf-tokens"
dynamic = ["version"]
description = "ALCF client to interface with various services"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "typer",
    "globus-sdk>=4",
    "httpx",
]

[project.scripts]
alcf-tokens = "alcf_tokens.cli:cli"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.ruff]
line-length = 88
target-version = "py310"
